FROM openjdk:11
ENV APP_PATH=/app
WORKDIR $APP_PATH
COPY /build/libs/stock.jar ./
EXPOSE 8003
CMD java \
  -jar stock.jar \
  --CONFIG_CONNECTION=${CONFIG_SERVICE_CONNECTION} \
  --DISCOVERY_CONNECTION=${DISCOVERY_SERVICE_CONNECTION} \
  --KAFKA_CONNECTION=${KAFKA_SERVICE_CONNECTION} \
  --DB_CONNECTION=${DB_SERVICE_CONNECTION} \
  --DB_USERNAME=${DB_USER} \
  --DB_PASSWORD=${DB_PASS}